
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://psryoyugyimibjhwhvlh.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzcnlveXVneWltaWJqaHdodmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4NTM2NDMsImV4cCI6MjA0OTQyOTY0M30.HqVFT7alWrZtjf1cHxeAeqpsWMjVEnnXfVtwesYga-0'

export const supabase = createClient(supabaseUrl, supabaseKey)
